CREATE TABLE [dbo].[CompraInteligenteLog](
	[Id] [smallint] IDENTITY(1,1) NOT NULL,
	[Data] [datetime] NULL,
	[Descricao] [varchar](50) NULL,
	[Log] [varchar](600) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


